name: Create-resource

on:
    workflow_dispatch:

jobs:
    Windows:
        runs-on: windows-2022

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Create resource
          shell: cmd
          run: |
            set __VSCMD_ARG_NO_LOGO=1
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            mkdir new-res
            copy /y rc\clear-icon-cache.rc new-rc\clear-icon-cache.rc
            copy /y rc\recopy-shortcut-arrow.rc new-rc\recopy-shortcut-arrow.rc
            copy /y rc\restore-shortcut-arrow.rc new-rc\restore-shortcut-arrow.rc
            cd new-res
            rc /n /nologo clear-icon-cache.rc
            rc /n /nologo remove-shortcut-arrow.rc
            rc /n /nologo restore-shortcut-arrow.rc

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
              name: new-res
              path: |
                new-res
